name: ScryiOS
options:
  deploymentTarget:
    iOS: 15.0

settings:
  base:
    PRODUCT_NAME: ScryiOS
    
packages:
  SwiftLint:
    url: https://github.com/realm/SwiftLint.git
    from: 0.55.1

targets:
  ScryiOS:
    type: application
    platform: iOS
    sources:
      - path: ScryiOS
    info:
      path: ScryiOS/Resources/Info.plist
      properties:
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    settings:
      base:
        INFOPLIST_FILE: ScryiOS/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    configFiles:
      Debug: Config/Development.xcconfig
      Release: Config/Distribution.xcconfig
    dependencies:
      - package: SwiftLint
        product: SwiftLintBuildToolPlugin
        type: plugin