name: SwiftLint

on:
  pull_request:
    paths:
      - '**/*.swift'
      - '.swiftlint.yml'
  push:
    branches: [ main, master, develop ]
    paths:
      - '**/*.swift'
      - '.swiftlint.yml'

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --strict --config .swiftlint.yml